
		<main>
			<section class="bloc3">
				<div>
					<h2>
						Yves <span>KAERCHER</span><br/>
						Développeur Web / <span>Intégrateur</span>
					</h2>
				</div>
			</section>
			<section class="bloc3 contact-form">
				<h3>Fomulaire de contact :</h3>
					<div id="contact_results"></div>
					<div>
						<form id="contact_form" method="POST">
							<div id="contact-form-name">
								<span><i class="fa fa-user"></i></span>
								<input type="text" name="contact-form-name" placeholder="Nom" required="true"/> 
							</div>
 							<div id="contact-form-phone">
								<span><i class="fa fa-phone"></i></span>
								<input type="text" name="contact-form-phone" placeholder="Tel" />
							</div>
							<div id="contact-form-email">
								<span><i class="fa fa-envelope"></i></span>
								<input type="email" name="contact-form-email" placeholder="Email" required="true"/> 
							</div>
							<div id="contact-form-subject">
								<span><i class="fa fa-paper-plane"></i></span>
								<input type="text" name="contact-form-subject" placeholder="Objet" required="true"/> 
							</div>
							<div id="contact-form-message">
								<span><i class="fa fa-comment"></i></span>
								<textarea name="contact-form-message" placeholder="Message" rows="6" required="true"></textarea> 
							</div>
							<div id="contact-form-submit"><input type="submit" value="Envoyer"></div>
						</form>
					</div>
			</section>
		</main>

<body>
