<body>
<div class="wrapper">
		<header>
			<div id='logo'>
				<a href='index.php?page=page0'><img src='resources/images/yk-logo.png' alt='logo YK'/></a>
				<h1>Yves <span>KAERCHER</span> <small>Développeur/Intégrateur</small></h1>
			</div>
			
			<nav id='nav'>
				<ul>
					<li><a href='index.php?page=page0' class='home' > Accueil</a></li>
					<li><a href='index.php?page=page1' class='projets'>Projets</a></li>
					<li><a href='index.php?page=page2' class='contact'>Contact</a></li>
					<li><a href='index.php?page=page3' class='login'>Login</a></li>
				</ul>
			</nav>
		</header>		
		<main>
			<section class="bloc3">
				<div>
					<h2>
						Yves <span>KAERCHER</span><br/>
						Développeur Web / <span>Intégrateur</span>
					</h2>
				</div>
			</section>
			<section class="bloc3 contact-form">
				<h3>Fomulaire de contact :</h3>
					<div id="contact_results"></div>
					<div>
						<form id="contact_form" method="POST">
							<div id="contact-form-name">
								<span><i class="fa fa-user"></i></span>
								<input type="text" name="contact-form-name" placeholder="Nom" required="true"/> 
							</div>
 							<div id="contact-form-phone">
								<span><i class="fa fa-phone"></i></span>
								<input type="text" name="contact-form-phone" placeholder="Tel" />
							</div>
							<div id="contact-form-email">
								<span><i class="fa fa-envelope"></i></span>
								<input type="email" name="contact-form-email" placeholder="Email" required="true"/> 
							</div>
							<div id="contact-form-subject">
								<span><i class="fa fa-paper-plane"></i></span>
								<input type="text" name="contact-form-subject" placeholder="Objet" required="true"/> 
							</div>
							<div id="contact-form-message">
								<span><i class="fa fa-comment"></i></span>
								<textarea name="contact-form-message" placeholder="Message" rows="6" required="true"></textarea> 
							</div>
							<div id="contact-form-submit"><input type="submit" value="Envoyer"></div>
						</form>
					</div>
			</section>
		</main>
		<footer>
			<nav id='footer-nav'>
					<ul>
						<li><a href='index.php?page=page0' class='home' > Accueil</a></li>
						<li><a href='index.php?page=page1' class='projets'>Projets</a></li>
						<li><a href='index.php?page=page3' class='login'>Login</a></li>
					</ul>
			</nav>
			<div id='footer-contact'>
					<ul>
						<li class='mail footer'><a href="mailto:ykaercher@gmail.com"> ykaercher@gmail.com</a></li>
						<li class='tel footer'> 06 68 71 25 70</li>
						<li class='LinkedIn footer'><a href="https://www.linkedin.com/in/yves-kaercher-70a475aa/" target="_blank"> LinkedIn</a></li>
					</ul>
			</div>
			<div id='footer-copyright'>
				<p class='copyright'><i class="fa fa-copyright" aria-hidden="true"></i>2017</p>
			</div>
		</footer>
	</div>
<body>
