
        <main>
            <section class="bloc3">
                <div>
                    <h2>
						Yves <span>KAERCHER</span><br/>
						Développeur Web / <span>Intégrateur</span>
					</h2> </div>
            </section>
            <section class="bloc3 contact-form">
                <h3>Fomulaire d'inscription :</h3>
                <div id="contact_results"></div>
                <div>
                    <form id="contact-form" action="apps/sign-up.php" method="POST">
                        <div id="contact-form-email"> <span><i class="fa fa-envelope"></i></span>
                            <input type="email" name="email" placeholder="Mail" required="true" /> </div>
                        <div id="contact-form-name"> <span><i class="fa fa-user"></i></span>
                            <input type="text" name="username" placeholder="Pseudo" required="true" /> </div>
                        <div id="contact-form-subject"> <span><i class="fa fa-key"></i></span>
                            <input type="password" name="passwordHash" placeholder="Mdp" required="true" /> </div>
                        <div id="contact-form-submit">
                            <input type="submit" value="Envoyer" /> </div>
                    </form>
                </div>
            </section>
        </main>


