
<body>
<!--[if lte IE 9]>
<p class="browsehappy">Vous utilisez un navigateur <strong>dépassé</strong>. Merci de <a href="http://browsehappy.com/">mettre à jour votre navigateur</a> pour améliorer votre expérience sur ce site.</p>
<![endif]-->
	<div class="wrapper">
		<header>
			<div id='logo'>
				<a href='./index.php?page=home'><img src='./resources/images/yk-logo.png' alt='logo YK'/></a>
				<h1>Yves <span>KAERCHER</span> <small>Développeur/Intégrateur</small></h1>
			</div>
			
			<nav id='nav'>
				<ul>
					<li><a href='./index.php?page=home' class='home' > Accueil</a></li>
					<li><a href='./index.php?page=page1' class='projets'>Projets</a></li>
					<li><a href='./index.php?page=page2' class='contact'>Contact</a></li>
					<?php if(!isset($user['username'])) {?>
						<li><a href='./index.php?page=page3' class='login'>Login</a></li>
					<?php } ?> 
				</ul>
			</nav>
		</header>	
	<body>
		<main>
			<section class="bloc3">
				<div>
					<h2>
						Yves <span>KAERCHER</span><br/>
						Développeur Web / <span>Intégrateur</span>
					</h2>
				</div>
			</section>
			<section class="bloc2">
				<h3>Compétences</h3>
				<div class="col"> 
					<p>HTML5/CSS3</p> <progress max="100" value="90"></progress>
					<p>PHP/MYSQL</p> <progress class="php" max="100" value="80"></progress>
					<p>JAVASCRIPT</p> <progress max="100" value="70"></progress>
					<p>JQUERY (UI)</p> <progress max="100" value="60"></progress>
					<p>POO</p>	<progress max="100" value="60"></progress>
					<p>RESPONSIVE DESIGN</p> <progress max="100" value="50"></progress>
				</div>
				<div class="col">
					<p><img src="./resources/images/csshtmljss.png" /></p>
					<p><img src="./resources/images/php2.png" /></p>
					<p><img src="./resources/images/mysql1.png" /></p>
					<p><img src="./resources/images/jquery1.png" /></p>
				</div>
			</section>
			<section class="bloc1 parcour">
				<h3>Parcour</h3>
				<div>
					
					<p>
						Issu d'une formation en Electronique, j'ai toujours orienté ma carrière vers l'informatique, si bien que j'ai créé ma propre entreprise en 1997 sous le nom Caisse Computer Système. J'ai démarré en installant des terminaux point de vente et j'ai continué de me former sur des systèmes plus complexes comme les serveurs de domaine des serveurs TSE pour administrer des réseaux. En 2007 la société change de nom et devient Crystal Informatique. Pendant 17 ans, au grès des besoins je me suis auto formé aux technologies de l'informatique.

					</p>
					<p>
						Mon goût croissant pour ce domaine m'a amené à  me lancer dans le développement.
						Dans ce but, j'ai opté pour une formation qualifiante à la :(<a  href="https://3wa.fr/">3W Académy</a>), afin de donner un cadre plus professionnel à mes connaissances, ainsi que découvrir certaines nouvelles technologies.
					</p>
					<p>
						Aujourd’hui, j'ai enfin atteint mes objectifs qui étaient d'avoir un panel complet dans la maîtrise de l'informatique au service de l'entreprise.
					</p>
					
				</div>
			</section>
			<section class="bloc1 scale CV">
				<h3>CV</h3>
				<div>
					<a href="./resources/files/CV_Yves_Kaercher.pdf" target="_blank"><img src="./resources/images/CV.png" alt="CV"/></a>
				</div>
			</section>
			<section class="bloc2 ">
				<h3>Expériences Professionnelles</h3>
				<div class="conteneur">
					<div id="carrousel">
						<div id="slide1" class="slide">
							<div class="visu">
								<a href="#" target="_blank">
									<img class="img" src="./resources/images/ccs.jpg" alt="ccs"/>
									<p class="link" >www.caisse-computer.fr</p>
								</a>	
							</div>
							<div class="col1">
								<h4 class="title">Caisse Computer Système</h4>
								<p class="text">En 1997,en tant que gérant de la société, commercialisation de système d'encaissement pour le CHR vente de matériel informatique.</p>
							</div>

						</div>
						<div id="slide2" class="slide">
							<div class="visu">
								<a href="#" target="_blank">
									<img class="img" src="./resources/images/crystal1.jpg" alt="ccs"/>
									<p class="link" >www.crystal-info.fr</p>
								</a>	
							</div>
							<div class="col1">
								<h4 class="title">Crystal Informatique</h4>
								<p class="text">En 2007, en tant que gérant de la société, vente, installation de matériel informatique (serveurs, virtualisation, postes clients, périfériques, VOIP, caméras IP etc...) Administration de réseau, distributeur de solution métier Sage.</p>
							</div>

						</div>
						<div id="slide3" class="slide">
							<div class="visu">
								<a href="#" target="_blank">
									<img class="img" src="./resources/images/crisalid.png" alt="ccs"/>
									<p class="link" >www.crisalid.com</p>
								</a>	
							</div>
							<div class="col1">
								<h4 class="title">Crisalid Alsace</h4>
								<p class="text">En 2014, En charge du développement commercial des systèmes d'encaisssements dans le secteur nord de l'Alsace </p>
							</div>
						</div>
					</div>
				</div>
			</section>
		</main>
		<footer>
			<nav id='footer-nav'>
				<ul>
					<li><a href='./index.php?page=page1' class='projets'>Projets</a></li>
					<li><a href='./index.php?page=page2' class='contact'>Contact</a></li>
					<?php if(!isset($user['username'])) {?>
					<li><a href='./index.php?page=page3' class='login'>Login</a></li>
					<?php } ?>
				</ul>
			</nav>
			<div id='footer-contact'>
				<ul>
					<li class='mail'><a href="mailto:ykaercher@gmail.com"> ykaercher@gmail.com</a></li>
					<li class='tel'> 06 68 71 25 70</li>
					<li class='LinkedIn'><a href="https://www.linkedin.com/in/yves-kaercher-70a475aa/" target="_blank"> LinkedIn</a></li>
					<li>
						<?php if(isset($user['username'])) {?>
	                       	<h4>Bonjour : <?= htmlspecialchars($user['username']) ?>
	                        <button><a href="apps/sign-out.php">Se déconnecter</a></button></h4>
                    	<?php } ?>
                    </li>
				</ul>
			</div>
			<div id='footer-copyright'>
				<p class='copyright'><i class="fa fa-copyright" aria-hidden="true"></i>2017</p>
			</div>
		</footer>
	</div>
</body>
