		<main>
			<section class="bloc3">
				<div>
					<h2>
						
						Mes <span>Projets</span>
					</h2>
				</div>
			</section>

						<section class="bloc1 scale projet">
				<h3>Tableau de Bord</h3>
				<div class='loupe'>
						<p>
							<span>En cours de réalisation:</span> 2017<br/>
							<span>Description:</span><br/> Consultation en ligne des rapports d'un terminal point de vente						</p>
					</a>
				</div>
			</section>
						<section class="bloc1 scale projet">
				<h3></h3>
				<div class='loupe'>
					
							<span>Date de création:</span> 2017<br/>
							<span>Description:</span><br/> Interaction entre un site ecommerce et un système point de vente ( récupération des commandes en ligne directement sur la caisse et impression sur les postes de production.)						</p>
					</a>
				</div>


		</main>

</body>
