<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="fr-FR"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="description" value="" />
    <link rel="shortcut icon" type="image/png" href="./resources/images/yk-logo.png" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >


    <link rel="stylesheet" type="text/css" href="./resources/jquery/bootstrap-3.3.4/bootstrap.min.css"/ >
    <link rel="stylesheet" type="text/css" href="./resources/jquery/reset.css">
    <link rel="stylesheet" type="text/css" href="./resources/jquery/border-sizing.css">
    <link rel="stylesheet" type="text/css" href="./resources/jquery/jquery.bxslider.min.css">
    
    <link rel="stylesheet" type="text/css" href="./resources/css/font.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/layout.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/modules.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/theme.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/state.css">


    <script type="text/javascript" src="./resources/jquery/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="./resources/javascript/jquery.bxslider.min.js"></script>
    <script src="https://use.fontawesome.com/d1e621769b.js"></script>
    
   <title>Yves Kaercher Développeur/Intégrateur</title>
    
</head>
<body>

	<div class="wrapper">
		<header>
			<div id='logo'>
				<a href='index.php?page=page0'><img src='resources/images/yk-logo.png' alt='logo YK'/></a>
				<h1>Yves <span>KAERCHER</span> <small>Développeur/Intégrateur</small></h1>
			</div>
			
			<nav id='nav'>
				<ul>
					<li><a href='index.php?page=page0' class='home' > Accueil</a></li>
					<li><a href='index.php?page=page2' class='contact'>Contact</a></li>
					<li><a href='index.php?page=page3' class='login'>Login</a></li>
				</ul>
			</nav>
		</header>		<main>
			<section class="bloc3">
				<div>
					<h2>
						
						Mes <span>Projets</span>
					</h2>
				</div>
			</section>

						<section class="bloc1 scale projet">
				<h3>Tableau de Bord</h3>
				<div class='loupe'>
						<p>
							<span>En cours de réalisation:</span> 2017<br/>
							<span>Description:</span><br/> Consultation en ligne des rapports d'un terminal point de vente						</p>
					</a>
				</div>
			</section>
						<section class="bloc1 scale projet">
				<h3></h3>
				<div class='loupe'>
					
							<span>Date de création:</span> 2017<br/>
							<span>Description:</span><br/> Interaction entre un site ecommerce et un système point de vente ( récupération des commandes en ligne directement sur la caisse et impression sur les postes de production.)						</p>
					</a>
				</div>


		</main>
		<footer>
			<nav id='footer-nav'>
					<ul>
						<li><a href='index.php?page=page0' class='home' > Accueil</a></li>
						<li><a href='index.php?page=page1' class='projets'>Projets</a></li>
						<li><a href='index.php?page=page2' class='contact'>Contact</a></li>
						<li><a href='index.php?page=page3' class='login'>Login</a></li>
					</ul>
				</nav>
			<div id='footer-contact'>
					<ul>
						<li class='mail footer'><a href="mailto:ykaercher@gmail.com"> ykaercher@gmail.com</a></li>
						<li class='tel footer'> 06 68 71 25 70</li>
						<li class='LinkedIn footer'><a href="https://www.linkedin.com/in/yves-kaercher-70a475aa/" target="_blank"> LinkedIn</a></li>
					</ul>
				</div>
			<div id='footer-copyright'>
				<p class='copyright'></p>
			</div>
		</footer>
	</div>
	<script type="text/javascript" src="resources/javascript/script.js"></script>
</body>
</html>