<body>

	<div class="wrapper">
		<header>
			<div id='logo'>
				<a href='index.php?page=page0'><img src='resources/images/yk-logo.png' alt='logo YK'/></a>
				<h1>Yves <span>KAERCHER</span> <small>Développeur/Intégrateur</small></h1>
			</div>
			
			<nav id='nav'>
				<ul>
					<li><a href='index.php?page=page0' class='home' > Accueil</a></li>
					<li><a href='index.php?page=page2' class='contact'>Contact</a></li>
					<li><a href='index.php?page=page3' class='login'>Login</a></li>
				</ul>
			</nav>
		</header>		<main>
			<section class="bloc3">
				<div>
					<h2>
						
						Mes <span>Projets</span>
					</h2>
				</div>
			</section>

						<section class="bloc1 scale projet">
				<h3>Tableau de Bord</h3>
				<div class='loupe'>
						<p>
							<span>En cours de réalisation:</span> 2017<br/>
							<span>Description:</span><br/> Consultation en ligne des rapports d'un terminal point de vente						</p>
					</a>
				</div>
			</section>
						<section class="bloc1 scale projet">
				<h3></h3>
				<div class='loupe'>
					
							<span>Date de création:</span> 2017<br/>
							<span>Description:</span><br/> Interaction entre un site ecommerce et un système point de vente ( récupération des commandes en ligne directement sur la caisse et impression sur les postes de production.)						</p>
					</a>
				</div>


		</main>
		<footer>
			<nav id='footer-nav'>
					<ul>
						<li><a href='index.php?page=page0' class='home' > Accueil</a></li>
						<li><a href='index.php?page=page1' class='projets'>Projets</a></li>
						<li><a href='index.php?page=page2' class='contact'>Contact</a></li>
						<li><a href='index.php?page=page3' class='login'>Login</a></li>
					</ul>
				</nav>
			<div id='footer-contact'>
					<ul>
						<li class='mail footer'><a href="mailto:ykaercher@gmail.com"> ykaercher@gmail.com</a></li>
						<li class='tel footer'> 06 68 71 25 70</li>
						<li class='LinkedIn footer'><a href="https://www.linkedin.com/in/yves-kaercher-70a475aa/" target="_blank"> LinkedIn</a></li>
					</ul>
				</div>
			<div id='footer-copyright'>
				<p class='copyright'></p>
			</div>
		</footer>
	</div>
</body>
