<!DOCTYPE html>
<html class="no-js" lang="fr-FR">

<head>
	<meta charset="utf-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1">
	<!--<meta name="description" value="" />-->
	<link rel="shortcut icon" type="image/png" href="./resources/images/yk-logo.png">
	

	<link rel="stylesheet" type="text/css" href="./resources/jquery/carrousel.css" media="screen"/>
	<link rel="stylesheet" type="text/css" href="./resources/jquery/bootstrap-3.3.4/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" href="./resources/css/normalize.css">

 	<link rel="stylesheet" type="text/css" href="./resources/css/font.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/layout.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/modules.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/theme.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/state.css">

	<script src="http://code.jquery.com/jquery-3.2.1.js"integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="crossorigin="anonymous"></script>
	<script src="https://use.fontawesome.com/d1e621769b.js"></script>

	<title>Yves Kaercher Développeur/Intégrateur</title>

</head>
<body>
		<div class="wrapper">
		<header>
			<div id='logo'>
				<a href='./index.php?page=home'><img src='./resources/images/yk-logo.png' alt='logo YK'/></a>
				<h1>Yves <span>KAERCHER</span> <small>Développeur/Intégrateur</small></h1>
			</div>
			
			<nav id='nav'>
				<ul>
					<li><a href='./index.php?page=home' class='home' > Accueil</a></li>
					<li><a href='./index.php?page=page1' class='projets'>Projets</a></li>
					<li><a href='./index.php?page=page2' class='contact'>Contact</a></li>
					<?php if(!isset($user['username'])) {?>
						<li><a href='./index.php?page=page3' class='login'>Membres</a></li>
					<?php } ?> 
				</ul>
			</nav>
		</header>	
	



<!-- **********   !!!  Partie indispensable !!!   ************** -->

		<?php require("./apps/".$page.".php"); ?> <!-- On recupère la page demandée avec $page et intégre son contrôleur-->

<!-- ************************************************************* -->

			<footer>
			<nav id='footer-nav'>
				<ul>
					<li><a href='./index.php?page=page1' class='projets'>Projets</a></li>
					<li><a href='./index.php?page=page2' class='contact'>Contact</a></li>
					<?php if(!isset($user['username'])) {?>
					<li><a href='./index.php?page=page3' class='login'>Membres</a></li>
					<?php } ?>
				</ul>
			</nav>
			<div id='footer-contact'>
				<ul>
					<li class='mail'><a href="mailto:ykaercher@gmail.com"> ykaercher@gmail.com</a></li>
					<li class='tel'> 06 68 71 25 70</li>
					<li class='LinkedIn'><a href="https://www.linkedin.com/in/yves-kaercher-70a475aa/" target="_blank"> LinkedIn</a></li>
					<li>
						<?php if(isset($user['username'])) {?>
	                       	<h4>Bonjour : <?= htmlspecialchars($user['username']) ?>
	                        <button><a href="apps/sign-out.php">Se déconnecter</a></button></h4>
                    	<?php } ?>
                    </li>
				</ul>
			</div>
			<div id='footer-copyright'>
				<p class='copyright'><i class="fa fa-copyright" aria-hidden="true"></i>2017</p>
			</div>
		</footer>
	</div>

	<script type="text/javascript" src="./resources/javascript/script.js"></script>
	<script type="text/javascript" src="./resources/javascript/carrousel1.js"></script>
</body>
</html>
