<!DOCTYPE html>
<!-- [if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""><![endif] -->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang=""><![endif]-->
<!-- [if IE 8]> <html class="no-js lt-ie9" lang=""> <![endif] -->
<!-- [if gt IE 8]>--><html class="no-js" lang="fr-FR"><!--<![endif]-->

<head>
	<meta charset="utf-8">
	<meta name="description" value="" />
	<link rel="shortcut icon" type="image/png" href="./resources/images/yk-logo.png" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0" >


	<link rel="stylesheet" type="text/css" href="./resources/jquery/bootstrap-3.3.4/bootstrap.min.css"/ >
	<link rel="stylesheet" type="text/css" href="./resources/jquery/reset.css">
	<link rel="stylesheet" type="text/css" href="./resources/jquery/border-sizing.css">
	<link rel="stylesheet" type="text/css" href="./resources/jquery/jquery.bxslider.min.css">
	
 	<link rel="stylesheet" type="text/css" href="./resources/css/font.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/layout.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/modules.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/theme.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/state.css">


	<script type="text/javascript" src="./resources/jquery/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="./resources/javascript/jquery.bxslider.min.js"></script>
	<script src="https://use.fontawesome.com/d1e621769b.js"></script>
	
	<title>Yves Kaercher Développeur/Intégrateur</title>

</head>
<body>
	



<!-- **********   !!!  Partie indispensable !!!   ************** -->

		<?php require("./apps/".$page.".php"); ?> <!-- On recupère la page demandée avec $page et intégre son contrôleur-->

<!-- ************************************************************* -->




</body>
</html>
